# Site settings
title: Better Homes & Gardens Real Estate
tagline: "Changing the world, one uninspired quote at a time"
url: "http://yourwebsite.com" # The base hostname & protocol for your site. Use it if you need absolute URL's


# Use this for production
sass:
   style: compressed

exclude: [.scss, README.md, node_modules, gruntfile.js, package.json]
